kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demochat-canary
  namespace: codefresh-demochat-canary
  creationTimestamp: '2017-12-07T18:23:05Z'
  labels:
    app: demochat
    release: canary
  annotations:
    deployment.kubernetes.io/revision: '2'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demochat
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demochat
      annotations:
    spec:
      containers:
        - name: demochat
          image: 'r.cfcr.io/sakibulhasan-wsib_github/olegscodefresh/demochat:canary'
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: MONGO_DOCKER
              value: 'mongodb://mongo'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 40
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: codefresh-generated-r.cfcr.io-cfcr-default
      schedulerName: default-scheduler
