apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demochat-canary
  namespace: codefresh-demochat-canary
  creationTimestamp: '2017-12-07T18:23:05Z'
  labels:
    app: demochat
    release: canary
  name: demochat-canary
  namespace: codefresh-demochat-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demochat
  template:
    metadata:
      labels:
        app: demochat
    spec:
      containers:
      - env:
        - name: MONGO_DOCKER
          value: mongodb://mongo
        image: r.cfcr.io/sakibulhasan-wsib_github/olegscodefresh/demochat:canary
        imagePullPolicy: Always
        name: demochat
        ports:
        - containerPort: 5000
          protocol: TCP
      imagePullSecrets:
      - name: codefresh-generated-r.cfcr.io-cfcr-codefresh-demochat-canary
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 40
